### ISSUE TITLE
Tag repository so we can pin version

### ISSUE THREAD

**Issue by rstml** [dbt-athena/dbt-athena-external-tables#5]
Can maintainer please tag the latest version so we can use pinned version such as:

```
   - git: "https://github.com/dbt-athena/dbt-external-tables-athena"
     revision: 0.0.1
```

Using `main` is live environment is dangerous as new changes can break things.

**Comment by brabster** [comment]
Pending the maintainers' decision on how they want to manage releases, you can pin to the latest commit (which you can get from the time-ordered [commits list](https://github.com/dbt-athena/dbt-athena-external-tables/commits/main/)).

```yml
  - git: https://github.com/dbt-athena/dbt-athena-external-tables
    revision: 4502217f9c6e40f497dc21996c19552b4d58e177
```

```console
06:20:29  Installing https://github.com/dbt-athena/dbt-athena-external-tables
06:20:31  Installed from revision 4502217f9c6e40f497dc21996c19552b4d58e177
```

**Comment by nicor88** [comment]
@rstml https://github.com/dbt-athena/dbt-athena-external-tables/releases/tag/v0.0.1
Somehow I was not getting notifications for this repo.
What @brabster it's a recommended approach in general when you cannot point to a release/tag, and you want to avoid to use main/master branch.
Anyhow, now we have the tag.
